{
  "type": "record",
  "name": "AvroSubtaskUpdatedEvent",
  "namespace": "com.vrudenko.kanban_board.event.avro",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "userId", "type": "string" },
    { "name": "boardId", "type": "string" },
    { "name": "taskId", "type": "string" },
    { "name": "subtaskId", "type": "string" },
    { "name": "isCompleted", "type": "boolean" },
    { "name": "timestamp", "type": { "type": "long", "logicalType": "timestamp-millis" } }
  ]
}
