package com.vrudenko.kanban_board.event;

import java.time.Instant;

/**
 * Shared contract for every domain event published to kanban.activity: plain records with
 * no Lombok, JPA or Spring annotations, because producer and consumer share the package.
 *
 * Decisions:
 *
 * Events carry identifiers, actor and timestamp only (plus server-derived state such as a
 * position or isCompleted), never user-authored text such as a title, description or name.
 *
 * boardId is mandatory on every event rather than derived by the consumer: the listener
 * runs with no SecurityContext and never re-verifies ownership, so whatever an event
 * carries is trusted downstream as-is.
 *
 * eventId is a String, not a java.util.UUID: it is generated by
 * EventIdGenerator, a thin wrapper around the time-ordered, Base36 RandFlakeGenerator
 * behind every entity primary key, not a random identifier.
 */
public sealed interface ActivityEvent
        permits TaskCreatedEvent,
                TaskMovedEvent,
                TaskDeletedEvent,
                TaskUpdatedEvent,
                BoardCreatedEvent,
                BoardUpdatedEvent,
                BoardDeletedEvent,
                ColumnCreatedEvent,
                ColumnDeletedEvent,
                ColumnUpdatedEvent,
                ColumnReorderedEvent,
                SubtaskCreatedEvent,
                SubtaskUpdatedEvent,
                SubtaskDeletedEvent {
    String eventId();

    String userId();

    String boardId();

    Instant timestamp();
}
