package com.vrudenko.kanban_board.event;

import java.time.Instant;

/**
 * Shared contract for every domain event this application publishes to {@code kanban.activity}.
 * Plain, dependency-free records only — no Lombok, no JPA, no Spring annotations — because this
 * package is shared by the producer (this phase) and Phase 3's consumer.
 *
 * <p>{@code boardId} is mandatory on every event, not derived by the consumer: Phase 3's listener
 * runs with no {@code SecurityContext} and never re-verifies ownership, so whatever this
 * interface's implementations carry is trusted downstream as-is.
 *
 * <p>{@code eventId} is a {@link String}, not a {@link java.util.UUID} (GAP-07): every event id is
 * generated by {@code EventIdGenerator}, a thin wrapper around this project's existing
 * time-ordered, Base36-encoded {@code RandFlakeGenerator} — the same generator behind every entity
 * primary key — rather than a randomly generated identifier.
 */
public sealed interface ActivityEvent
        permits TaskCreatedEvent,
                TaskMovedEvent,
                TaskDeletedEvent,
                TaskUpdatedEvent,
                BoardCreatedEvent,
                BoardUpdatedEvent,
                BoardDeletedEvent,
                ColumnCreatedEvent,
                ColumnDeletedEvent,
                ColumnUpdatedEvent,
                ColumnReorderedEvent,
                SubtaskCreatedEvent,
                SubtaskUpdatedEvent,
                SubtaskDeletedEvent {
    String eventId();

    String userId();

    String boardId();

    Instant timestamp();
}
