package com.vrudenko.kanban_board.event;

import java.time.Instant;

/**
 * Shared contract for every domain event published to {@code kanban.activity}: plain records with
 * no Lombok, JPA or Spring annotations, because producer and consumer share the package.
 *
 * <p>Decisions:
 *
 * <p>Events carry identifiers, actor and timestamp only (plus server-derived state such as a
 * position or {@code isCompleted}), never user-authored text such as a title, description or name.
 *
 * <p>{@code boardId} is mandatory on every event rather than derived by the consumer: the listener
 * runs with no {@code SecurityContext} and never re-verifies ownership, so whatever an event
 * carries is trusted downstream as-is.
 *
 * <p>{@code eventId} is a {@link String}, not a {@link java.util.UUID}: it is generated by {@code
 * EventIdGenerator}, a thin wrapper around the time-ordered, Base36 {@code RandFlakeGenerator}
 * behind every entity primary key, not a random identifier.
 */
public sealed interface ActivityEvent
        permits TaskCreatedEvent,
                TaskMovedEvent,
                TaskDeletedEvent,
                TaskUpdatedEvent,
                BoardCreatedEvent,
                BoardUpdatedEvent,
                BoardDeletedEvent,
                ColumnCreatedEvent,
                ColumnDeletedEvent,
                ColumnUpdatedEvent,
                ColumnReorderedEvent,
                SubtaskCreatedEvent,
                SubtaskUpdatedEvent,
                SubtaskDeletedEvent {
    String eventId();

    String userId();

    String boardId();

    Instant timestamp();
}
