apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - platform.yaml
  - data.yaml
  - apps-nonprod.yaml
  - cert-manager.yaml
  - edge.yaml
  - apps-prod.yaml
  - monitoring-controllers.yaml
  - monitoring.yaml
  - image-automation.yaml
