name: CI/CD with Docker

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USER: rudenkovladimir
  DOCKERHUB_REPOSITORY: kanban-board-backend

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Create environment variables
        run: echo "BASE_IMAGE_NAME=${DOCKERHUB_USER}/${DOCKERHUB_REPOSITORY}" >> $GITHUB_ENV

  run-tests:
    runs-on: ubuntu-latest
    needs: setup
    if: success()
    steps:
      - name: Run tests
        run: ./gradlew test

      - name: Run Spotless
        run: ./gradlew spotlessCheck

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USER --password-stdin

      # need to add a tag to image to not cause name collisions on dockerhub when pushing
      - name: Set image tag from commit
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set full image name
        run: echo "ACTUAL_IMAGE_NAME=${BASE_IMAGE_NAME}:${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $ACTUAL_IMAGE_NAME .

      - name: Push Docker image
        run: docker push $ACTUAL_IMAGE_NAME

  deploy-to-ec2:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
#          1. install docker if not installed; 2. stop old container, start a new one using new image
      - name: Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
             if ! command -v docker &> /dev/null; then
               echo "Docker not found. Installing..."
               sudo apt update
               sudo apt install -y docker.io
               sudo systemctl enable docker
               sudo systemctl start docker
               sudo usermod -aG docker $(whoami)
               newgrp docker
             else
               echo "Docker is already installed."
             fi

            sudo docker pull $ACTUAL_IMAGE_NAME
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker run -d --name myapp -p 80:8080 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
            $ACTUAL_IMAGE_NAME
            sudo docker image prune -af
          EOF

  cleanup-old-images:
    runs-on: ubuntu-latest
    needs: deploy-to-ec2
    if: success()
    steps:
      # we need to do that because we only want to have a single active prod deployment for that project
      - name: Delete old Docker Hub images
        run: |
          # Get list of all tags
          TAGS=$(curl -s -u "$DOCKERHUB_USER:${{ secrets.DOCKERHUB_TOKEN }}" \
            "https://hub.docker.com/v2/repositories/$BASE_IMAGE_NAME/tags/" \
            | jq -r '.results[].name')

          # Delete all tags except the current one
          for TAG in $TAGS; do
            if [ "$TAG" != "$IMAGE_TAG" ]; then
              echo "Deleting tag: $TAG"
              curl -s -X DELETE -u "$DOCKERHUB_USER:${{ secrets.DOCKERHUB_TOKEN }}" \
                "https://hub.docker.com/v2/repositories/$BASE_IMAGE_NAME/tags/$TAG/"
            fi
          done




  # if deployment failed, we need to cleanup the image we pushed, because it won't be used
  cleanup-unused-image:
    runs-on: ubuntu-latest
    needs: deploy-to-ec2
    if: failure()
    steps:
      - name: Remove just-pushed image
        run: |
          REPO_NAME=$(echo "$BASE_IMAGE_NAME" | cut -d/ -f2)
          echo "Deleting failed tag: $IMAGE_TAG"
          curl -s -X DELETE -u "$DOCKERHUB_USER:${{ secrets.DOCKERHUB_TOKEN }}" \
            "https://hub.docker.com/v2/repositories/$BASE_IMAGE_NAME/tags/$IMAGE_TAG/"